name: Marriage
version: 2.0
main: com.lenis0012.bukkit.marriage2.internal.MarriagePlugin
author: lenis0012
description: A plugin wich provides the function to start a relationship in minecraft.
dev-url: http://dev.bukkit.org/bukkit-mods/marriage-reloaded/
softdepend: [Vault]
commands:
  marry:
    description: Marriage main command.
    usage: /marry <args>
permissions:
  marry.*:
    description: Allows all Marriage Commands
    default: false
    children:
      marry.admin:
        description: Allows all admin commands
        default: false
        children:
          marry.reload:
            description: Allows to reload the config files
            defalt: op
          marry.priest:
            description: Allows player to marry 2 orther players.
            default: false
          marry.chatspy:
            description: Allows player to view all mchat.
            default: op
      marry.default:
        description: Allows default player commands
        default: true
        children:
          marry.marry:
            description: Allows to marry with players
            default: true
          marry.chat:
            description: Allows to chat with your partner
            default: true
          marry.tp:
            description: Allows to tp to your partner
            default: true
          marry.home:
            description: Allows to tp to your home if set
            default: true
          marry.sethome:
            description: Allwos to set your Marriage home
            default: true
          marry.gift:
            description: Allows to gift itesm to your partner
            default: true
          marry.chat:
            description: Allows to chat with your partner
            default: true
          marry.child:
            description: Allows everything with children in marriage.
            default: true
          marry.seen:
            description: Allows to see your last login from your partner
            default: true